"""
app/models/complaint.py
-----------------------
Core complaint record. Every other table in this schema hangs off this one
via foreign keys.

complaint_number generation strategy
-------------------------------------
Pattern: CMP-{YYYY}-{NNNN}  e.g. "CMP-2026-0001"

We intentionally do NOT use a server_default or computed column here because
the year component must reflect the *year the complaint was received*, not the
year the row was physically inserted (these can differ near year-end if a
complaint arrives on Dec 31 but hits the DB on Jan 1).

Instead, the service layer does:
    seq  = await db.scalar(text("SELECT nextval('complaint_number_seq')"))
    num  = f"CMP-{received_year}-{seq:04d}"

A PostgreSQL sequence `complaint_number_seq` is created in the Alembic
migration to make this atomic.  This approach:
  * Keeps the number meaningful/human-readable
  * Avoids trigger complexity
  * Is still race-condition-safe (sequences are transactional in Postgres)

Nullability decisions
----------------------
* complainant_contact — nullable.  Paper/phone complaints may arrive without a
  contact if the complainant is anonymous; regulatory reporting still requires
  the complaint to be logged.
* severity — nullable until AI triage runs (can take seconds to minutes).
  Never block complaint intake waiting for an LLM call.
* batch_no — NOT NULL; required for product traceability. If unknown, the
  complainant must provide "UNKNOWN" so the field is always populated.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    BigInteger, DateTime, Enum as SAEnum,
    String, Text, UniqueConstraint, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.enums import Category, Severity, SourceType, Status


class Complaint(Base):
    __tablename__ = "complaints"

    __table_args__ = (
        UniqueConstraint("complaint_number", name="uq_complaints_number"),
        {
            "comment": (
                "Primary complaint record. Every field change MUST produce an "
                "audit_log entry to satisfy 21 CFR Part 11 audit-trail requirements."
            )
        },
    )

    # ------------------------------------------------------------------ #
    # Primary key                                                          #
    # ------------------------------------------------------------------ #
    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=True
    )

    # Human-readable identifier — generated by service layer, see module docstring.
    complaint_number: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        unique=True,
        comment="CMP-YYYY-NNNN format. Generated by app service using complaint_number_seq.",
    )

    # ------------------------------------------------------------------ #
    # Product / batch identification                                        #
    # ------------------------------------------------------------------ #
    product_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Trade name or INN of the medicinal product.",
    )

    batch_no: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment=(
            "Batch/lot number required for product traceability. "
            "Use 'UNKNOWN' if not available — do NOT leave blank."
        ),
    )

    # ------------------------------------------------------------------ #
    # Complainant information                                              #
    # ------------------------------------------------------------------ #
    complainant_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # Nullable: anonymous complaints, paper forms without contact info.
    complainant_contact: Mapped[Optional[str]] = mapped_column(
        String(320),    # 320 = max RFC 5321 email length (safe for phone too)
        nullable=True,
        comment="Email or phone. NULL for anonymous submissions.",
    )

    # ------------------------------------------------------------------ #
    # Classification fields                                                #
    # ------------------------------------------------------------------ #
    source_type: Mapped[SourceType] = mapped_column(
        SAEnum(SourceType, name="sourcetype", create_type=True),
        nullable=False,
        comment="Channel through which the complaint was received.",
    )

    category: Mapped[Category] = mapped_column(
        SAEnum(Category, name="category", create_type=True),
        nullable=False,
        comment="Regulatory complaint category. adverse_event triggers additional reporting.",
    )

    # NULL until AI assessment runs — intentional.
    severity: Mapped[Optional[Severity]] = mapped_column(
        SAEnum(Severity, name="severity", create_type=True),
        nullable=True,
        comment=(
            "NULL = not yet assessed. Populated by the AI triage agent. "
            "Human QA officer can override."
        ),
    )

    status: Mapped[Status] = mapped_column(
        SAEnum(Status, name="status", create_type=True),
        nullable=False,
        server_default="new",
        comment="Complaint lifecycle state. Every change must be logged to audit_log.",
    )

    # ------------------------------------------------------------------ #
    # Content                                                              #
    # ------------------------------------------------------------------ #
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full verbatim complaint description as received.",
    )

    # ------------------------------------------------------------------ #
    # Timestamps                                                           #
    # ------------------------------------------------------------------ #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Auto-updated on any field change by SQLAlchemy's onupdate hook.",
    )

    # ------------------------------------------------------------------ #
    # Relationships (back-populated from child tables)                    #
    # ------------------------------------------------------------------ #
    documents: Mapped[list["ComplaintDocument"]] = relationship(   # noqa: F821
        "ComplaintDocument",
        back_populates="complaint",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    assessments: Mapped[list["AIAssessment"]] = relationship(      # noqa: F821
        "AIAssessment",
        back_populates="complaint",
        foreign_keys="AIAssessment.complaint_id",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    audit_logs: Mapped[list["AuditLog"]] = relationship(           # noqa: F821
        "AuditLog",
        back_populates="complaint",
        cascade="all, delete-orphan",
        order_by="AuditLog.timestamp",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return f"<Complaint {self.complaint_number} status={self.status}>"


# Import child models at the bottom to avoid circular imports at module load.
from app.models.complaint_document import ComplaintDocument  # noqa: E402, F401
from app.models.ai_assessment import AIAssessment            # noqa: E402, F401
from app.models.audit_log import AuditLog                    # noqa: E402, F401
